### ISSUE TITLE
Cancellable Progress Bar for Sync All 

### ISSUE THREAD

**Issue by mahaloz** [binsync/binsync#133]
When you click Sync All for a user this functions triggers:
https://github.com/angr/binsync/blob/37aee8b6c891973944d983c7cd138d6e6ff742af/binsync/common/controller.py#L403

Which essentially iterates all the functions for a user and attempts to fill each one. This process and be long (~5mins) and may be too much for the user. We need to make a progress bar here that can be canceled. Note for this to be a good solution it must be implemented in the common UI.

**Comment by arizvisa** [comment]
Not sure if you want to rip this because it's Qt, but https://github.com/arizvisa/ida-minsc/blob/master/misc/ui.py#L1387. I wanted to dumb down the api to make it so that I could send updates to it every once in a while.

After instantiating it, you can just call update every once in a while with the attributes you want to change.
```
    P.open()
    P.update(current=0, max=len(funcs), title=u"Pre-building the tag cache and its index...")
    P.close()
```

You can poll `P.canceled`, but really you should probably connect the event to your UI directly.

**Comment by mahaloz** [comment]
Ooooh @arizvisa I like a lot of this code. The only thing I am worried about is the events that it emits since that changed between PyQt5 and PySide2. Our UI is wack in that it supports PyQt5, PySide2, and PySide6 (since each decompiler uses a different Qt version).

**Comment by arizvisa** [comment]
damn, that's a shame. :-/
ui work is always the most painful for me, heh.

**Comment by mahaloz** [comment]
I'm closing this, since it's become clear that it's not feasible in IDA. When we have dialogs popping up to confirm things, it makes it impossible to get the focus on our popup.
