### ISSUE TITLE
`Enter` key in Configuration dialog moves focus back main window

### ISSUE THREAD

**Issue by mborgerson** [binsync/binsync#190]
* Running on Ubuntu 22.04, IDA 8.0
* Open 'Configure BinSync' dialog
* Enter fields
* Press <kbd>Enter</kbd> key to accept the dialog. Instead of accepting the dialog, focus actually moves back to IDA main window, with the dialog left open.
* Behavior is similar to #187

**Comment by mahaloz** [comment]
Both with #187 and this, I've also encountered this issue a few times. I recall @frqmod spent something like 10 hours trying to diagnose the issue, since this is not what happens in angr-management binsync. We speculate it has something to do with PyQT and how IDA steals focus for windows. I'll mark this for now, but it may end up being a wontfix situation.

**Comment by frqmod** [comment]
I actually have a fix for this, but it needs to be elegantly implemented, turns out the intended way to do this is to use one of IDA's UI Hooks (https://www.hex-rays.com/products/ida/support/idapython_docs/ida_kernwin.html#ida_kernwin.UI_Hooks.preprocess_action) to preprocess their global commands, which we can then hand off to our widgets. Ideally we implement this without too much encroaching on the common codebase.
