### ISSUE TITLE
Binary Ninja import system prioritizes packaged Python

### ISSUE THREAD

**Issue by mahaloz** [binsync/binsync#241]
### Description

While developing on multiple versions of BinSync, I've found that if you install our plugin with the Binary Ninja Plugin system, then uninstall, then install manually, you will only be able to use the old library code the Binary Ninja Plugin Manager installed. See steps below.

### Steps to reproduce the bug

1. Install `binsync` through the Binary Ninja Plugin manager, it will pip install `binsync>=3.2.3`
2. Uninstall it
3. Manually install `binsync` of a different version to your local Python, I did version `binsync==3.0.0`
4. Now go into the Binja Python interpreter window and you will observe the following:
```python
>>> import binsync
>>> binsync.__version__
'3.2.3'
```

The version should be `3.0.0`, but it's not. Uninstalling the plugin did not uninstall the `binsync` lib, and this becomes a problem when it fights with an install on your local Python. This is all because Binja prioritizes its Python over your local one in the Python Path:
```python
>>> sys.path
['/home/mahaloz/.binaryninja/repositories/official/plugins', '/home/mahaloz/.binaryninja/repositories/community/plugins', '/home/mahaloz/.binaryninja/plugins', '/home/mahaloz/.binaryninja/python310/site-packages/git/ext/gitdb', '/home/mahaloz/.binaryninja/python310/site-packages', '/home/mahaloz/ctf/tools/binja/binaryninja/plugins/../python3', '/home/mahaloz/ctf/tools/binja/binaryninja/plugins/../python', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/mahaloz/.local/lib/python3.10/site-packages', '/home/mahaloz/github/binsync']
```

The only way I could solve this without messing with the Path here was to destroy the `binsync` package inside the binary ninja site-packages: 
`rm -f /home/mahaloz/.binaryninja/python310/site-packages/binsync*`

### Additional context

I don't think this is something we can fix on our side.

**Comment by psifertex** [comment]
Unfortunately I don't think this is really fixable in BN either without something much more complicated than we have now and is probably best suited toward documentation describing the edge case and manual solutions.

In particular, we don't want to automatically remove dependencies of a plugin when the plugin itself is removed since _another_ plugin might also have the same dependency, or depend on a module that recursively has that dependency. 

I don't see a potential solution except maybe every time a plugin is removed, uninstalling its requirements and then also refreshing _every other plugin's requirements_ at that time which is a bit of a headache.

Not sure, I want to think it over some more but it mostly comes down to the fact that pip isn't really a package manager. There's no apt autoclean equivalent because pip doesn't really track things like that afaik.

**Comment by psifertex** [comment]
Oh -- I should point out though that if you re-install the plugin in Binary Ninja, it _will_ correctly replace the binsync with the more recent one (though this requires a relatively recent dev build and not the stable) so that's at least one simple work-around.

**Comment by mahaloz** [comment]
@psifertex I followed up a little in slack, but I think the real issue is that even when I specify that I want binja to use my Python, it still has Binja Python in the path before mine.

**Comment by mahaloz** [comment]
Closing this for now unless is somehow comes up again.

**Comment by psifertex** [comment]
Yeah, we're gonna talk over the options internally some more and see if we can come up with some tweaks to the current workflow.
