### ISSUE TITLE
Refactor angr-binsync to use workspace-less plugin system 

### ISSUE THREAD

**Issue by mahaloz** [binsync/binsync#254]
### Description

Watching PR https://github.com/angr/angr-management/pull/963, it looks like workspace will be destroyed from angr-management, which will result in the complete failure of the BinSync plugin since right now we directly rely on Workspace for all our references to decompilation. 

This needs to be refactored after the linked PR lands.

**Comment by twizmwazin** [comment]
Workspace isn't going away, we're just improving abstractions so that we can eventually have a more sane API for angr management. The main change to be aware of right now is just that instances won't be aware of the workspace, if there is one. Workspaces can still subscribe to instance containers, however.

**Comment by mahaloz** [comment]
@twizmwazin after this commit: https://github.com/angr/angr-management/commit/aa6ce2127f05b8e2056850f11e104b91acf17295, all of BinSync is broken on angr-management :(
