### ISSUE TITLE
`ValueError` from configuration dialog

### ISSUE THREAD

**Issue by alexrp** [binsync/binsync#294]
### Description

```
Traceback (most recent call last):
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\ui\config_dialog.py", line 164, in _on_repo_clicked
    path = path.with_suffix(".bsproj")
  File "pathlib.py", line 782, in with_suffix
ValueError: WindowsPath('.') has an empty name
```

### Steps to reproduce the bug

Unfortunately, I'm not exactly sure what I did to trigger this exception. I can't seem to repro it, and things are working fine now. Hopefully the backtrace rings a bell to someone.

### Environment

Binary Ninja 3.5.4311-dev Personal (ff27871c)

**Comment by mahaloz** [comment]
@alexrp so strangely, I think this is a race condition inside BinSync. You might be able to reproduce this by opening a binary for the first time in binary ninja (no bndb), quickly go and configure binsync before the whole binary finishes loading in Binja. 

My hunch is that this is caused by the BV not being fully initialized when we ask for it, resulting in an `empty` name on the binary, resulting in this.

**Comment by alexrp** [comment]
Hmm, I think in my case, I triggered it on a fully open and idle BV where I wanted to connect to a repo.

Come to think of it, I did manually delete a `.bsproj` directory that I had used previously. I then recreated it with the `New` button in the configuration dialog. I wonder if something went wrong in that process?

**Comment by mahaloz** [comment]
Lmao, no this is just a real bug. I'll have the fix up in 10.
