### ISSUE TITLE
Force Push Freezes UI

### ISSUE THREAD

**Issue by domenukk** [binsync/binsync#394]
### Description

In Ghidra, when I hit "Force Push" with a large number of functions (around 35k), the UI freezes.
It will only unfreeze when I close the CodeBrowser Window.
After closing, the forcepush menu pops up and shows the option to push a bunch of functions.
Of course, pushing then doesn't work (as the window is closed).

### Steps to reproduce the bug

- Open file with many functions
- Force push
- Beachball

### Environment

MacOS, Ghidra 11.1.2, current binsync from pip

**Comment by mahaloz** [comment]
@domenukk ok, this ideally has been fixed in #397. Turns out the problem had nothing to do with the function amount. It's the fact that their are 100k symbols that we try to iterate to find global vars... which is dumb. For now we just stop for those if it's too large.

The impact on data you see will be pretty minimal. You will still see all funcs, enums, structs, and typedefs. 

To update, simply use `pip install -U binsync`. It should be version `v4.8.1` now. On my Mac on a 20mb binary, it took about 9 seconds for the window to render for me.

**Comment by domenukk** [comment]
Thank you, I'll try it out later.
FWIW I saw you're doing everything in a for loop via the ghidra bridge.
I assume for every single eval you need an RPC call from python 3 to python 2 and back, including (de)serializations.
When working on my own little iterator, I had _intense_ performance improvements by instead switching to remote_eval to get a list of the symbols I wanted, like so:
https://github.com/domenukk/strudra/blob/3c618779f9a9cf646d145e3ab703a0b4e7dbb767/strudra/strudra.py#L727

**Comment by mahaloz** [comment]
@domenukk that timing issue you had earlier was already with the remote eval :(. Haha, you wouldn't know it at first glance, but we have `remote_eval` under the hood all over the place. Like here:
https://github.com/binsync/libbs/blob/86ae9291ba19b54f5460b9266a40a21c628653ec/libbs/decompilers/ghidra/interface.py#L1126

`@ui_remote_eval` does some function parsing and runs it over the bridge if the client is in bridge mode (when using BinSync). However, in script mode, it is natively evaluated in Python 3 (Pyhidra).

**Comment by domenukk** [comment]
Slow things being slow..
Anyway thanks for the fix :)
